### ISSUE TITLE
Scrolling on Edge browser

### ISSUE THREAD

**Issue by Trisk3lion** [danielperna84/hass-configurator#128] opened 2018-11-09 11:24 UTC
I noticed that when using Microsoft Edge I can't scroll inside the code window, the browser tries to scroll that page instead (which isn't possible). It the same behavior when using my trackpad and using touch.

**Comment by danielperna84** [comment] 2018-11-09 13:43
Could you please try the demo editor on https://ace.c9.io/ and see if the problem is present there too (add a couple of new lines, at some point scrollbars will appear)? This would tell us if the problem is caused by how we embedded the editor or if it is the editor itself that has problems.

**Comment by danielperna84** [comment] 2018-11-10 11:55
I just tried myself and don't have any problems in Egde. So I'm not sure what the problem could be and how to reproduce it. Are you using some kind of touchscreen device?

**Comment by Trisk3lion** [comment] 2018-11-10 14:41
It's the same for me in demo editor on https://ace.c9.io/.
I'm using a Surface Go, so yes it's a touchscreen device with Windows precision drivers for the trackpad.

I connected a regular mouse and then it works as it should, I guess this means that it's something with the touchscreen scrolling and windows precision drivers?

**Comment by danielperna84** [comment] 2018-11-10 20:37
Yes, with that info it's pretty clear, that your issue is device specific, and not related to the configurator itself (as you also experience the same issue with the plain Ace editor). Hence I'm closing this issue for now.

**Closed by danielperna84** 2018-11-10 20:37 UTC
