### ISSUE TITLE
Consider mirroring external dependencies

### ISSUE THREAD

**Issue by osctobe** [danielperna84/hass-configurator#209] opened 2021-01-16 20:19 UTC
Currently hass-configurator requires client device to be connected to the internet to work. This makes it problematic to use its service on a secured network without risking user data leaking out. Please consider mirroring the dependencies, so that all resources are served from Home Assistant server and no Internet access is needed to use the app.

**Comment by danielperna84** [comment] 2021-01-17 10:48
Duplicate of #177

**Closed by danielperna84** 2021-01-17 10:48 UTC
