### ISSUE TITLE
No access to configutator after installing letsencrypt.

### ISSUE THREAD

**Issue by MarioHA** [danielperna84/hass-configurator#48] opened 2017-08-12 15:20 UTC
As in title, installed add on in Hassio and was working as intended. Next installed letsencrypt and can no longer access configurator via https. Tried uninstalling and reinstalling to no avail. Any help would be appreciated.

**Comment by danielperna84** [comment] 2017-08-12 16:18
Since I am not using hassio myself I can't really help with that. My first guess would be:
When running HASS with SSL, it does not support iframes which don't use SSL. So you have to explicitly enable SSL for the configurator as well, and of course setup the port forwarding so you can access the configurator via the hostname that's used in the certificate. In case that's how you plan to use it, you definitely have to set a username and password, or else your configuration would be accessible to the internet.
If this does not help, I woul ask you to post your issue in the thread in the community: https://community.home-assistant.io/t/repository-hass-configurator/17838
I'm pretty sure there will be someone with a similar setup to yours who can help solve your issue. And if it gets solved, please post the solution here as well so it's documented along with this issue and I can close it. :)

**Comment by danielperna84** [comment] 2017-08-17 23:11
I have another thought why you may not be able to connect: with SSL enabled you will probably first go outside to the internet, and from there back to your home network. Your client IP address will be the external one of your modem. The configurator has an option `ALLOWED_NETWORKS`, which by default only accepts a few generic ones. Your public IP won't fall into this category, hence blocking access. To allow connections from anywhere you have to add `0.0.0.0` to the list of allowed networks. I would not recommend doing that though, since this would disable the generally blocking nature of the configurator. If possible, figure out the IP-ranges your ISP is using and add those instead. That way you at least lock out machines that are not within your ISPs network.

**Comment by danielperna84** [comment] 2017-08-31 12:13
After getting no response after 2 weeks I assume the issue has been resolved and was caused by the local setup. Closing the issue.

**Closed by danielperna84** 2017-08-31 12:13 UTC

**Comment by MarioHA** [comment] 2017-08-31 20:47
Sorry, been busy lately.
The issue was never resolved but I removed letsencrypt and then had no issues.
Thanks.

**Comment by AalianKhan** [comment] 2018-06-18 17:19
I had the same issue but then in the search bar I wrote the IP address of my Pi then 3218 eg. `192.168.0.43:3218` and it worked. by the way, I was inside of my network.
