### ISSUE TITLE
Users reporting issues with Home Assistant  File Editor "unknown tag" error for the "!include" values

### ISSUE THREAD

**Issue by loganmarchione** [danielperna84/hass-configurator#226] opened 2022-09-08 02:46 UTC
See [this issue](https://github.com/home-assistant/addons/issues/2656) for full details.

After updating to Home Assistant File Editor 5.4.0, which is based on hass-configurator 0.5.0, users (myself included) are reporting issues with "unknown tag" error for the "!include" values. Again, see the other issue for logs and screenshots.

**Comment by danielbrunt57** [comment] 2022-09-08 09:04
`!include` within homeassistant: section being flagged:

![image](https://user-images.githubusercontent.com/49846893/189081631-c72aff17-77d6-4c98-b686-9460f2768e07.png)

![image](https://user-images.githubusercontent.com/49846893/189081996-d3cc7a2e-2e91-4f3f-872b-c815e4b6320f.png)

Other `!include`'s are fine.

**Comment by danielperna84** [comment] 2022-09-08 16:36
This must be a result of updating the `js-yaml` dependency. There has been no change to relevant code: https://github.com/danielperna84/hass-configurator/compare/0.4.1...0.5.0

[Here](https://github.com/danielperna84/hass-configurator/blob/7d4d1ebc176f1a5ff7ae0a94a8a5d24b4e4fc3a0/hass_configurator/dev.html#L2977) is the part where such exceptions are handled, and `include` is still present.

Does anybody have an idea why we're having this issue?

**Comment by danielbrunt57** [comment] 2022-09-08 17:39
More testing... It's always and only the first `!(include|secret|env_var|input)` in the file that gets flagged.

**Comment by danielperna84** [comment] 2022-09-08 18:07
It's only the first instance, because it's causing js-yaml to fail at loading the whole content of the file. As a result, no linting at all will be done, as the yaml can't be parsed.

I don't get why this is happening though. Executing the code manually properly replaces all occurrences of the keywords, and thus succeeds to load the yaml eventually.

**Comment by danielperna84** [comment] 2022-09-08 18:49
Actually, I have come to believe that it's not js-yaml that is causing the problem. js-yaml is only used for the icon next to the filename that's either a green check mark or a red exclamation mark.

The linting error we're seeing in the editor seems to be a feature of the upgraded Ace Editor.

**Comment by danielbrunt57** [comment] 2022-09-08 19:05
If I introduce some other error like bad indentation, I first see the ("check_circle") with ("grey-text") when lint is queued followed by ("cursor-pointer red-text") with the error line flagged by the X in red box.  Fixing the error shows ("check_circle") ("grey-text") followed by ("green-text") which would indicate the lint test passed but yet the first !(include|secret|env_var|input) is flagged with X in red box.

**Comment by danielbrunt57** [comment] 2022-09-08 19:05
> The linting error we're seeing in the editor seems to be a feature of the upgraded Ace Editor.

Ah!

**Comment by danielperna84** [comment] 2022-09-08 19:07
The error can be hidden manually via the JS console with the statement: `editor.getSession().setAnnotations([]);`

The question remains how we can either hide the error automatically, or turn off linting in Ace without also breaking the syntax highlighting or other language-specific features.

**Comment by loganmarchione** [comment] 2022-09-08 19:25
> The linting error we're seeing in the editor seems to be a feature of the upgraded Ace Editor.

Can you rollback the editor version to verify? Is this something we need to report upstream to Ace?

**Comment by danielperna84** [comment] 2022-09-08 19:32
I am able to disable linting by disabling the workers (`editor.session.setOption("useWorker", false);`). This keeps syntax highlighting intact, which is the main feature we want in the editor. Back then Ace didn't have yaml-linting, but now it does. Hence we now get the error.

This is not a problem with Ace Editor, as the keywords are custom to Home Assistant. I have yet to find a way if it's possible to configure Ace in such a way, that the internal linting also ignores certain keywords. The implementation we already had in older version were kind of a _hack_ (replacing _bad_ keywords with allowed ones on the fly). This may not be possible with Ace. So disabling linting altogether probably is the only thing we can do.

**Comment by danielbrunt57** [comment] 2022-09-08 20:03
Might [this ](https://gist.github.com/olegch/37212ba350cabca921fd3109df2d1981)be relevant or provide insight as to how to permit the 4 HA custom tags in js-yaml?

**Comment by danielperna84** [comment] 2022-09-08 20:06
With the configurator loading external files isn't that easy and requires some effort. To get rid of the bug in the short term I went with disabling the linting within Ace. That shouldn't be a problem for anyone just working with yaml files, as the old yaml-linting is working as designed. Hence I already release a bugfix release. Right now I'm in the process of creating the PR to also update the add-on.

If someone want's to get the native linting back, they're free to create a PR here with the required changes. So to me this issue can be closed as soon as the add-on-PR has been merged.

**Comment by danielbrunt57** [comment] 2022-09-08 20:10
Another answer I found is [https://stackoverflow.com/questions/40977113/js-yaml-issue-with-tags](https://stackoverflow.com/questions/40977113/js-yaml-issue-with-tags):
Take a look at [examples/custom_types.js](https://github.com/nodeca/js-yaml/blob/f6bafed1c4d82e80ab3fc3a71a5af63308f54b2f/examples/custom_types.js) in the js-yaml repo. The solution is to create a new jsyaml.Type that tells js-yaml to treat !Status values as mappings, like so:

let StatusYamlType = new jsyaml.Type('!Status', { kind: 'mapping' });
Then you need to create a new Schema that includes the StatusYamlType type:

let STATUS_SCHEMA = jsyaml.Schema.create([ StatusYamlType ]);
Finally, pass the new STATUS_SCHEMA to jsyaml.safeLoad via the schema option:

jsyaml.safeLoad(doc, { schema: STATUS_SCHEMA });

**Comment by danielbrunt57** [comment] 2022-09-08 20:14
Disregard the previous suggestion as this would have to be done inside the ACE editor...

**Closed** 2022-10-12 22:55 UTC
Labels: help wanted
